@hostname = 127.0.0.1
@port=9007
@contentType=application/json

@name=login

@tokenValue=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJsa2QiLCJpYXQiOjE2MTI0NDY0ODAsIm1vYmlsZSI6IjEzODAwMDAwMDAwIiwidXNlcklkIjoxLCJsb2dpblR5cGUiOjAsImV4cCI6MTYxMjQ0NjQ4MH0.fmFdhhj7gS4dp8weMx-du461cbgZlqiE-42x_k9KxBY



####运营运维登录####
POST http://{{hostname}}:{{port}}/user-service/user/login HTTP/1.1
Content-Type: {{contentType}}

{
    "mobile":"13700000002",
    "code":"35697",
    "loginType":1
}


#####生成短信验证码####
GET http://{{hostname}}:{{port}}/user-service/user/code/13700000002 HTTP/1.1
Content-Type: {{contentType}}



#########operatorList####

GET http://{{hostname}}:{{port}}/userService/user/operatorList
Authorization: {{tokenValue}}


######创建补货工单######################
POST http://{{hostname}}:{{port}}/task-service/task/create
Authorization: {{tokenValue}}
Content-Type: {{contentType}}

{
    "createType":1,
    "innerCode":"01000001",
    "assignorId":4,
    "productType":2,
    "details":[
      {"channelCode":"1-1","expectCapacity":1,"skuId":1,"skuName":"可口可乐"},
      {"channelCode":"1-2","expectCapacity":2,"skuId":1,"skuName":"可口可乐"}
    ]
}

######创建投放工单######################
POST http://{{hostname}}:{{port}}/task-service/task/create
Authorization: {{tokenValue}}
Content-Type: {{contentType}}

{
    "createType":1,
    "innerCode":"01000002",
    "assignorId":6,
    "productType":1,
    "desc":"投放"
}


#######接受工单###################
GET http://{{hostname}}:{{port}}/task-service/task/accept/24
Authorization: {{tokenValue}}
Content-Type: {{contentType}}


########取消（拒绝）工单############

POST  http://{{hostname}}:{{port}}/task-service/task/cancel/6
Authorization: {{tokenValue}}
Content-Type: {{contentType}}

{
    "desc":"累了"
}


###完成工单#####
GET http://{{hostname}}:{{port}}/task-service/task/complete/7 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}


###完成工单(采集坐标)#####
GET http://{{hostname}}:{{port}}/task-service/task/complete/24?lat=39.987282&lon=116.355546 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}

#########工单列表http://{{hostname}}:{{port}}/taskService/task/all

POST http://{{hostname}}:{{port}}/taskService/task/all HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}

{
    "userId":0,
    "start":"2019-01-01 00:00:00",
    "end":"2019-12-01 00:00:00",
    "pageIndex": 1,
    "pageSize": 10
}

####工单实时汇总###
GET http://{{hostname}}:{{port}}/task-service/task/taskReportInfo/2021-01-01 00:00:00/2021-01-31 23:59:59 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}

#####工作量排名####
GET http://{{hostname}}:{{port}}/task/rank/6 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}

### 工单状态统计 ####
GET http://{{hostname}}:{{port}}/task-service/task/collectReport/2020-11-01/2020-11-30 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}

####用户工作量####
GET http://{{hostname}}:{{port}}/task-service/task/userWork?userId=6&start=2021-01-01 00:00:00&end=2021-10-31 00:00:00 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}



####用户工作量列表####
GET http://{{hostname}}:{{port}}/user-service/user/searchUserWork?pageIndex=1&pageSize=10 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}


####人效排名月度统计###
GET http://{{hostname}}:{{port}}/task-service/task/userWorkTop10/2021-01-01/2021-01-31/true/1339752425761804289 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{tokenValue}}



