stages:
  - sonar

sonar_analyze:
  stage: sonar
  script:
    - |
      sonar-scanner -X \
      -Dsonar.projectKey=gitlab:$CI_COMMIT_REF_NAME:$CI_PROJECT_NAME \
      -Dsonar.projectName=$CI_PROJECT_NAME \
      -Dsonar.projectVersion=1.0.$CI_PIPELINE_ID \
      -Dsonar.sources=src \
      -Dsonar.sourceEncoding=UTF-8
  tags:
    - centos-aliyun-158
  only:
    - master